import { Context, h } from 'koishi'
import { Config } from '../config'
import {
  ApiClient,
  resolveOutputModes,
  getTypstRenderer,
  buildTypstTheme,
  escapeTypstText,
} from '../index'

interface PlayersCountResponse {
  count: number
}

function formatTextOutput(data: PlayersCountResponse): string {
  return `🔢 玩家数量

👥 当前在线: ${data.count} 人`
}

function generateTypstCode(data: PlayersCountResponse, theme: ReturnType<typeof buildTypstTheme>): string {
  const timestamp = new Date().toLocaleString('zh-CN')

  return `#set page(
  width: 350pt,
  height: auto,
  margin: (x: 14pt, y: 14pt),
  fill: ${theme.pageBg}
)

#set text(
  font: ("LXGW WenKai Mono", "Noto Sans CJK SC", "Microsoft YaHei"),
  size: 11pt,
  fill: ${theme.textColor},
  lang: "zh"
)

#align(center)[
  #block(
    fill: ${theme.headerFill},
    stroke: 2pt + ${theme.headerStroke},
    radius: 6pt,
    inset: 10pt,
    width: 100%
  )[
    #text(size: 16pt, weight: "bold", fill: ${theme.headerText})[
      🔢 玩家数量
    ]
  ]
]

#v(8pt)

#block(
  fill: ${theme.panelFill},
  stroke: 1pt + ${theme.panelStroke},
  radius: 4pt,
  inset: 16pt,
  width: 100%
)[
  #align(center)[
    #text(size: 32pt, weight: "bold", fill: ${theme.sectionTitle})[${data.count}]
    #v(4pt)
    #text(size: 12pt)[人在线]
  ]
]

#v(8pt)

#align(center)[
  #text(size: 8pt, fill: ${theme.statsText})[
    Generated by serverinfo-rest-client · ${escapeTypstText(timestamp)}
  ]
]
`
}

export function registerPlayersCountCommand(
  ctx: Context,
  cfg: Config,
  apiClient: ApiClient,
  logger: any
) {
  ctx.command('mcinfo.players-count', '玩家数量')
    .option('mode', '-m <mode:string> 输出模式 (text/image)')
    .action(async ({ session, options }) => {
      try {
        const data = await apiClient.get<PlayersCountResponse>('/players/count')
        const modes = resolveOutputModes(options.mode, cfg)

        const results: h[] = []

        for (const mode of modes) {
          if (mode === 'text') {
            results.push(h.text(formatTextOutput(data)))
          } else if (mode === 'typst-image') {
            try {
              const renderer = await getTypstRenderer(ctx, cfg, logger)
              const theme = buildTypstTheme(cfg)
              const typstCode = generateTypstCode(data, theme)
              const pngBuffer = await renderer.toPng(typstCode, cfg.typstRenderScale)
              results.push(h.image(pngBuffer, 'image/png'))
            } catch (err) {
              logger.warn(`Typst 渲染失败: ${err}`)
              results.push(h.text(`[Typst 渲染失败: ${err.message}]\n\n${formatTextOutput(data)}`))
            }
          }
        }

        if (cfg.quoteCommandReplies && session.messageId) {
          return h('', [h.quote(session.messageId), ...results])
        }
        return results
      } catch (error) {
        logger.error(`获取玩家数量失败: ${error}`)
        return `❌ 获取玩家数量失败: ${error.message}`
      }
    })
}
