import { Context, h } from 'koishi'
import { Config } from '../config'
import {
  ApiClient,
  resolveOutputModes,
  getTypstRenderer,
  buildTypstTheme,
  escapeTypstText,
} from '../index'

interface ServerResponse {
  bdsVersion: string
  protocolVersion: number
  onlinePlayers: number
  time: {
    daytime: number
    gametime: number
    day: number
  }
  weather: number
}

const WEATHER_MAP: Record<number, string> = {
  0: '☀️ 晴天',
  1: '🌧️ 雨天',
  2: '⛈️ 雷暴',
}

function getWeatherText(weather: number): string {
  return WEATHER_MAP[weather] || `❓ 未知 (${weather})`
}

function formatTextOutput(data: ServerResponse): string {
  return `🖥️ 服务器详细信息

🎮 BDS 版本: ${data.bdsVersion}
📡 协议版本: ${data.protocolVersion}
👥 在线玩家: ${data.onlinePlayers}

⏰ 时间信息:
  • 白天时间: ${data.time.daytime}
  • 游戏时间: ${data.time.gametime}
  • 游戏天数: 第 ${data.time.day} 天

🌤️ 天气: ${getWeatherText(data.weather)}`
}

function generateTypstCode(data: ServerResponse, theme: ReturnType<typeof buildTypstTheme>): string {
  const timestamp = new Date().toLocaleString('zh-CN')

  return `#set page(
  width: 420pt,
  height: auto,
  margin: (x: 14pt, y: 14pt),
  fill: ${theme.pageBg}
)

#set text(
  font: ("${theme.fontFamily}", "Noto Sans CJK SC", "Microsoft YaHei"),
  size: 11pt,
  fill: ${theme.textColor},
  lang: "zh"
)

#align(center)[
  #block(
    fill: ${theme.headerFill},
    stroke: 2pt + ${theme.headerStroke},
    radius: 6pt,
    inset: 10pt,
    width: 100%
  )[
    #text(size: 16pt, weight: "bold", fill: ${theme.headerText})[
      🖥️ 服务器详细信息
    ]
  ]
]

#v(8pt)

#block(
  fill: ${theme.panelFill},
  stroke: 1pt + ${theme.panelStroke},
  radius: 4pt,
  inset: 12pt,
  width: 100%
)[
  #text(weight: "bold", fill: ${theme.sectionTitle})[📋 基本信息]
  #v(6pt)
  #table(
    columns: (auto, 1fr),
    stroke: none,
    row-gutter: 6pt,
    
    [🎮 BDS 版本],
    [${escapeTypstText(data.bdsVersion)}],
    
    [📡 协议版本],
    [${data.protocolVersion}],
    
    [👥 在线玩家],
    [${data.onlinePlayers}],
    
    [🌤️ 天气],
    [${escapeTypstText(getWeatherText(data.weather))}],
  )
]

#v(8pt)

#block(
  fill: ${theme.panelFill},
  stroke: 1pt + ${theme.panelStroke},
  radius: 4pt,
  inset: 12pt,
  width: 100%
)[
  #text(weight: "bold", fill: ${theme.sectionTitle})[⏰ 时间信息]
  #v(6pt)
  #table(
    columns: (auto, 1fr),
    stroke: none,
    row-gutter: 6pt,
    
    [☀️ 白天时间],
    [${data.time.daytime}],
    
    [🕐 游戏时间],
    [${data.time.gametime}],
    
    [📅 游戏天数],
    [第 ${data.time.day} 天],
  )
]

#v(8pt)

#align(center)[
  #text(size: 8pt, fill: ${theme.statsText})[
    Generated by serverinfo-rest-client · ${escapeTypstText(timestamp)}
  ]
]
`
}

export function registerServerCommand(
  ctx: Context,
  cfg: Config,
  apiClient: ApiClient,
  logger: any
) {
  ctx.command('mcinfo.server', '服务器详细信息')
    .option('mode', '-m <mode:string> 输出模式 (text/image)')
    .action(async ({ session, options }) => {
      try {
        const data = await apiClient.get<ServerResponse>('/server')
        const modes = resolveOutputModes(options.mode, cfg)

        const results: h[] = []

        for (const mode of modes) {
          if (mode === 'text') {
            results.push(h.text(formatTextOutput(data)))
          } else if (mode === 'typst-image') {
            try {
              const renderer = await getTypstRenderer(ctx, cfg, logger)
              const theme = buildTypstTheme(cfg)
              const typstCode = generateTypstCode(data, theme)
              const pngBuffer = await renderer.toPng(typstCode, cfg.typstRenderScale)
              results.push(h.image(pngBuffer, 'image/png'))
            } catch (err) {
              logger.warn(`Typst 渲染失败: ${err}`)
              results.push(h.text(`[Typst 渲染失败: ${err.message}]\n\n${formatTextOutput(data)}`))
            }
          }
        }

        if (cfg.quoteCommandReplies && session.messageId) {
          return h('', [h.quote(session.messageId), ...results])
        }
        return results
      } catch (error) {
        logger.error(`获取服务器详细信息失败: ${error}`)
        return `❌ 获取服务器详细信息失败: ${error.message}`
      }
    })
}
