import { Context, h } from 'koishi'
import { Config } from '../config'
import {
  ApiClient,
  resolveOutputModes,
  getTypstRenderer,
  buildTypstTheme,
  escapeTypstText,
} from '../index'
import path from 'node:path'
import fs from 'node:fs'

const pkg = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '../package.json'), 'utf-8')
)
const CLIENT_VERSION = pkg.version

interface StatusResponse {
  status: string
  plugin: string
  version: string
  playerCount: number
  bdsVersion: string
  protocolVersion: number
}

function formatTextOutput(data: StatusResponse, label: string): string {
  const statusEmoji = data.status === 'online' ? '🟢' : '🔴'
  return `${label} 📊 服务器状态

${statusEmoji} 状态: ${data.status}
🔌 服务端插件: ${data.plugin} v${data.version}
🤖 Bot 客户端: v${CLIENT_VERSION}
👥 在线玩家: ${data.playerCount}
🎮 BDS 版本: ${data.bdsVersion}
📡 协议版本: ${data.protocolVersion}`
}

function generateTypstCode(data: StatusResponse, theme: ReturnType<typeof buildTypstTheme>, label: string): string {
  const timestamp = new Date().toLocaleString('zh-CN')
  const statusEmoji = data.status === 'online' ? '🟢' : '🔴'

  return `#set page(
  width: 400pt,
  height: auto,
  margin: (x: 14pt, y: 14pt),
  fill: ${theme.pageBg}
)

#set text(
  font: ("${theme.fontFamily}", "Noto Sans CJK SC", "Microsoft YaHei"),
  size: 11pt,
  fill: ${theme.textColor},
  lang: "zh"
)

#align(center)[
  #block(
    fill: ${theme.headerFill},
    stroke: 2pt + ${theme.headerStroke},
    radius: 6pt,
    inset: 10pt,
    width: 100%
  )[
    #text(size: 16pt, weight: "bold", fill: ${theme.headerText})[
      ${escapeTypstText(label)} 📊 服务器状态
    ]
  ]
]

#v(8pt)

#block(
  fill: ${theme.panelFill},
  stroke: 1pt + ${theme.panelStroke},
  radius: 4pt,
  inset: 12pt,
  width: 100%
)[
  #table(
    columns: (auto, 1fr),
    stroke: none,
    row-gutter: 8pt,
    align: (left, horizon),
    
    text(weight: "bold", fill: ${theme.sectionTitle})[${statusEmoji} 状态],
    [${escapeTypstText(data.status)}],
    
    text(weight: "bold", fill: ${theme.sectionTitle})[🔌 服务端插件],
    [${escapeTypstText(data.plugin)} v${escapeTypstText(data.version)}],
    
    text(weight: "bold", fill: ${theme.sectionTitle})[🤖 Bot 客户端],
    [v${escapeTypstText(CLIENT_VERSION)}],
    
    text(weight: "bold", fill: ${theme.sectionTitle})[👥 在线玩家],
    [${data.playerCount}],
    
    text(weight: "bold", fill: ${theme.sectionTitle})[🎮 BDS 版本],
    [${escapeTypstText(data.bdsVersion)}],
    
    text(weight: "bold", fill: ${theme.sectionTitle})[📡 协议版本],
    [${data.protocolVersion}],
  )
]

#v(8pt)

#align(center)[
  #text(size: 8pt, fill: ${theme.statsText})[
    Generated by serverinfo-rest-client · ${escapeTypstText(timestamp)}
  ]
]
`
}

export function registerStatusCommand(
  ctx: Context,
  cfg: Config,
  apiClient: ApiClient,
  logger: any,
  prefix: string,
  label: string
) {
  ctx.command(`${prefix}.status`, '服务器状态')
    .option('mode', '-m <mode:string> 输出模式 (text/image)')
    .action(async ({ session, options }) => {
      try {
        const data = await apiClient.get<StatusResponse>('/status')
        const modes = resolveOutputModes(options.mode, cfg)

        const results: h[] = []

        for (const mode of modes) {
          if (mode === 'text') {
            results.push(h.text(formatTextOutput(data, label)))
          } else if (mode === 'typst-image') {
            try {
              const renderer = await getTypstRenderer(ctx, cfg, logger)
              const theme = buildTypstTheme(cfg)
              const typstCode = generateTypstCode(data, theme, label)
              const pngBuffer = await renderer.toPng(typstCode, cfg.typstRenderScale)
              results.push(h.image(pngBuffer, 'image/png'))
            } catch (err) {
              logger.warn(`Typst 渲染失败: ${err}`)
              results.push(h.text(`[Typst 渲染失败: ${err.message}]`))
            }
          }
        }

        if (cfg.quoteCommandReplies && session.messageId) {
          return h('', [h.quote(session.messageId), ...results])
        }
        return results
      } catch (error) {
        logger.error(`获取服务器状态失败: ${error}`)
        return `❌ 获取服务器状态失败: ${error.message}`
      }
    })
}
